// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndiedwpcswkemrorjvjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kaWVkd3Bjc3drZW1yb3Jqdmp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2ODQ2MTUsImV4cCI6MjA1MDI2MDYxNX0.XmBb6Hwn4LafV3snsfg0xXvVITxaXUEhvj-V2kcY5FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);